//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MenusDBEntities : DbContext
    {
        public MenusDBEntities()
            : base("name=MenusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FoodDemandsTable> FoodDemandsTables { get; set; }
        public virtual DbSet<FoodTable> FoodTables { get; set; }
        public virtual DbSet<MenusTable> MenusTables { get; set; }
        public virtual DbSet<DailyScheduleProgram> DailySchedulePrograms { get; set; }
    }
}
