//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDemandsTable
    {
        public System.Guid RequestID { get; set; }
        public System.Guid FoodID { get; set; }
        public double Requested_Quantity { get; set; }
        public double Received_Quantity { get; set; }
        public System.DateTime Date_Order { get; set; }
    
        public virtual FoodTable FoodTable { get; set; }
    }
}
