//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodTable()
        {
            this.FoodDemandsTables = new HashSet<FoodDemandsTable>();
            this.MenusTables = new HashSet<MenusTable>();
        }
    
        public System.Guid FoodID { get; set; }
        public string Name { get; set; }
        public string UM { get; set; }
        public Nullable<double> Price_per_Unit { get; set; }
        public Nullable<double> Calories { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodDemandsTable> FoodDemandsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenusTable> MenusTables { get; set; }
    }
}
